#!/usr/bin/env python3
"""
Extract a compact node registry from n8n's built types/nodes.json files.

Reads the full INodeTypeDescription arrays generated by n8n's build pipeline
and produces a filtered node-registry.json containing only the fields the
nflow compiler needs: parameter names, types, defaults, valid values,
credentials, and connection types.

Usage:
    python3 scripts/extract-node-registry.py /path/to/n8n-repo [-o node-registry.json]

The n8n repo must have been built first (pnpm build).
"""

import argparse
import json
import os
import sys
from typing import Any


# Parameter types that produce no meaningful JSON output (UI-only).
UI_ONLY_TYPES = frozenset({
    'notice', 'callout', 'button', 'icon', 'curlImport',
})

# Parameter types that are pass-through (use default, no user input).
PASSTHROUGH_TYPES = frozenset({
    'hidden', 'credentials', 'credentialsSelect',
})

# Types that carry nested children.
NESTED_TYPES = frozenset({
    'collection', 'fixedCollection',
})


def filter_property(prop: dict) -> dict | None:
    """Filter a single INodeProperties entry to compiler-relevant fields."""
    ptype = prop.get('type', '')

    if ptype in UI_ONLY_TYPES:
        return None

    result: dict[str, Any] = {
        'name': prop['name'],
        'type': ptype,
    }

    if 'default' in prop:
        result['default'] = prop['default']

    if prop.get('required'):
        result['required'] = True

    # For options/multiOptions: extract valid values
    if ptype in ('options', 'multiOptions') and 'options' in prop:
        values = []
        for opt in prop['options']:
            if isinstance(opt, dict) and 'value' in opt:
                values.append(opt['value'])
        if values:
            result['values'] = values

    # For resourceLocator: extract available mode names
    if ptype == 'resourceLocator' and 'modes' in prop:
        result['modes'] = [m['name'] for m in prop['modes'] if isinstance(m, dict)]

    # For collection/fixedCollection: recurse into children
    if ptype in NESTED_TYPES and 'options' in prop:
        children = []
        for opt in prop['options']:
            if isinstance(opt, dict):
                if 'values' in opt:
                    # fixedCollection group: { name, values: INodeProperties[] }
                    group_children = filter_properties(opt['values'])
                    if group_children:
                        children.append({
                            'name': opt.get('name', ''),
                            'type': 'group',
                            'children': group_children,
                        })
                elif 'type' in opt:
                    # collection item: INodeProperties
                    filtered = filter_property(opt)
                    if filtered:
                        children.append(filtered)
        if children:
            result['children'] = children

    # For fixedCollection: note if it supports multiple values
    if ptype == 'fixedCollection':
        type_opts = prop.get('typeOptions', {})
        if type_opts.get('multipleValues'):
            result['multipleValues'] = True

    # For filter type: include typeOptions.filter if present
    if ptype == 'filter':
        type_opts = prop.get('typeOptions', {})
        if 'filter' in type_opts:
            result['filterConfig'] = type_opts['filter']

    # For resourceMapper: include typeOptions
    if ptype == 'resourceMapper':
        type_opts = prop.get('typeOptions', {})
        if type_opts:
            result['typeOptions'] = type_opts

    return result


def filter_properties(props: list[dict]) -> list[dict]:
    """Filter an array of INodeProperties, removing UI-only entries."""
    result = []
    for p in props:
        filtered = filter_property(p)
        if filtered:
            result.append(filtered)
    return result


def resolve_latest_version(version_field) -> float:
    """Get the latest version number from a version field (number or array)."""
    if isinstance(version_field, list):
        return max(version_field)
    return version_field


def normalize_connection_types(io_field) -> list[str]:
    """Normalize inputs/outputs to a list of connection type strings."""
    if isinstance(io_field, str):
        # Expression-based (dynamic) — can't resolve statically
        return ['dynamic']
    if isinstance(io_field, list):
        result = []
        for item in io_field:
            if isinstance(item, str):
                result.append(item)
            elif isinstance(item, dict):
                result.append(item.get('type', 'main'))
        return result
    return []


def extract_node(node: dict, package_prefix: str) -> tuple[str, dict]:
    """Extract a single node entry into the registry format.

    Returns (full_type_name, registry_entry).
    """
    name = node['name']
    full_name = f'{package_prefix}.{name}' if '.' not in name else name

    entry: dict[str, Any] = {
        'version': resolve_latest_version(node.get('version', 1)),
        'group': node.get('group', []),
        'inputs': normalize_connection_types(node.get('inputs', ['main'])),
        'outputs': normalize_connection_types(node.get('outputs', ['main'])),
        'defaultName': node.get('defaults', {}).get('name', ''),
    }

    # Credentials (keep name + required only)
    creds = node.get('credentials', [])
    if creds:
        entry['credentials'] = [
            {'name': c['name'], 'required': c.get('required', False)}
            for c in creds
        ]

    if node.get('polling'):
        entry['polling'] = True

    # Properties — the main payload
    props = filter_properties(node.get('properties', []))
    if props:
        entry['properties'] = props

    return full_name, entry


def extract_registry(n8n_repo: str) -> dict:
    """Build the full node registry from the n8n repo's built artifacts."""
    registry: dict[str, dict] = {}
    seen_latest: dict[str, float] = {}

    sources = [
        (os.path.join(n8n_repo, 'packages/nodes-base/dist/types/nodes.json'),
         'n8n-nodes-base'),
        (os.path.join(n8n_repo, 'packages/@n8n/nodes-langchain/dist/types/nodes.json'),
         '@n8n/n8n-nodes-langchain'),
    ]

    for path, prefix in sources:
        if not os.path.exists(path):
            print(f'Warning: {path} not found, skipping', file=sys.stderr)
            continue

        with open(path) as f:
            nodes = json.load(f)

        print(f'Loaded {len(nodes)} entries from {os.path.basename(os.path.dirname(os.path.dirname(path)))}',
              file=sys.stderr)

        for node in nodes:
            full_name, entry = extract_node(node, prefix)
            version = entry['version']

            # Keep only the latest version of each node
            if full_name in seen_latest:
                if version <= seen_latest[full_name]:
                    continue
            seen_latest[full_name] = version
            registry[full_name] = entry

    return registry


def extract_credentials(n8n_repo: str) -> dict:
    """Extract credential type definitions (name -> type info)."""
    path = os.path.join(n8n_repo, 'packages/nodes-base/dist/types/credentials.json')
    if not os.path.exists(path):
        return {}

    with open(path) as f:
        creds = json.load(f)

    result = {}
    for c in creds:
        name = c.get('name', '')
        if not name:
            continue
        entry: dict[str, Any] = {
            'displayName': c.get('displayName', ''),
        }
        # Extract credential properties (field names + types for the credential form)
        props = c.get('properties', [])
        if props:
            entry['fields'] = [
                {'name': p['name'], 'type': p.get('type', 'string')}
                for p in props
            ]
        result[name] = entry

    return result


def main():
    ap = argparse.ArgumentParser(
        description='Extract n8n node registry for nflow compiler.')
    ap.add_argument('n8n_repo', help='Path to the n8n repository (must be built)')
    ap.add_argument('-o', '--output', default='node-registry.json',
                    help='Output file (default: node-registry.json)')
    ap.add_argument('--include-credentials', action='store_true',
                    help='Include credential type definitions in output')
    ap.add_argument('--stats', action='store_true',
                    help='Print statistics about the extracted registry')
    args = ap.parse_args()

    registry = extract_registry(args.n8n_repo)
    print(f'Extracted {len(registry)} nodes', file=sys.stderr)

    output: dict[str, Any] = {
        '_meta': {
            'description': 'nflow node registry — extracted from n8n source',
            'nodeCount': len(registry),
        },
        'nodes': registry,
    }

    if args.include_credentials:
        creds = extract_credentials(args.n8n_repo)
        output['credentials'] = creds
        output['_meta']['credentialCount'] = len(creds)
        print(f'Extracted {len(creds)} credential types', file=sys.stderr)

    if args.stats:
        # Count property types across all nodes
        from collections import Counter
        type_counts = Counter()
        trigger_count = 0
        for entry in registry.values():
            if 'trigger' in entry.get('group', []):
                trigger_count += 1
            for p in entry.get('properties', []):
                type_counts[p['type']] += 1

        print(f'\nStatistics:', file=sys.stderr)
        print(f'  Total nodes: {len(registry)}', file=sys.stderr)
        print(f'  Trigger nodes: {trigger_count}', file=sys.stderr)
        print(f'  Property type distribution:', file=sys.stderr)
        for t, c in type_counts.most_common():
            print(f'    {t}: {c}', file=sys.stderr)

    with open(args.output, 'w') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    raw_size = os.path.getsize(args.output)
    print(f'Wrote {args.output} ({raw_size / 1024:.0f} KB)', file=sys.stderr)


if __name__ == '__main__':
    main()
