"""nflow — A compact DSL that compiles .nflow files into n8n workflow JSON."""

from nflow.compiler import (
    __version__,
    NflowError,
    generate_id,
    generate_condition_id,
    tokenize_with_lines,
    tokenize_lines,
    QUOTED_NAME,
    unquote_name,
    wrap_expr,
    parse_value,
    smart_split,
    parse_kv_block,
    find_unquoted,
    extract_block,
    extract_as_name,
    extract_flags,
    OPERATORS,
    parse_condition_line,
    parse_conditions_block,
    Node,
    Connection,
    KNOWN_KEYWORDS,
    N8nFDLParser,
    main,
)

__all__ = [
    "__version__",
    "NflowError",
    "N8nFDLParser",
    "Node",
    "Connection",
    "main",
    "tokenize_lines",
    "tokenize_with_lines",
    "parse_value",
    "smart_split",
    "parse_kv_block",
    "find_unquoted",
    "wrap_expr",
    "unquote_name",
    "extract_block",
    "extract_as_name",
    "extract_flags",
    "parse_condition_line",
    "parse_conditions_block",
    "QUOTED_NAME",
    "KNOWN_KEYWORDS",
    "OPERATORS",
    "generate_id",
    "generate_condition_id",
]
